# Generated by Django 2.2.20 on 2021-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='Rjjjjjjrrrr', help_text='Введите заголовок поста', max_length=50, verbose_name='Заголовок поста'),
            preserve_default=False,
        ),
    ]
